"""Wire-format schemas for the phone-to-Pi intent contract.

This module is the single source of truth for the JSON payload exchanged
between the phone client and the Pi's `/intent` endpoint. Both sides import
from here. Changes to these models break the wire format — bump
`SCHEMA_VERSION` when that happens.

The flow:

    phone: voice -> STT -> LLM -> IntentRequest (this schema)
          -> POST /intent -> Pi
    Pi:    IntentRequest -> py_trees tree -> tick -> IntentResponse
          -> reply -> phone
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field


SCHEMA_VERSION = "1.0.0"


Action = Literal[
    "move",
    "water",
    "water_all",
    "water_smart",
    "go_home",
    "light_on",
    "light_off",
    "photo",
    "panorama",
    "scan_weeds",
    "clear_weeds",
    "find_plants",
    "label_plants",
    "check_sensor",
    "check_moisture",
    "emergency_stop",
    "general_question",
]
"""Allowed action strings. Mirrors `AICore.ACTIONS` in the legacy package.
Adding an action here without a matching tree builder on the Pi is a bug."""


NodeStatus = Literal["success", "failure", "running", "skipped"]
TreeStatus = Literal["success", "failure", "partial"]
# IntentResponse status: a verified tree can take minutes, so /intent may reply
# "running" with a task_id the client polls on. Terminal values match TreeStatus.
ResponseStatus = Literal["success", "failure", "partial", "running"]


class Intent(BaseModel):
    """A single classified intent emitted by the LLM on the client side.

    An utterance may produce multiple `Intent` objects (e.g. "water the
    tomatoes and then go home" -> two intents). The Pi flattens these into one
    sequence tree.
    """

    action: Action
    target: Optional[str] = Field(
        default=None,
        description="Plant or location name from the garden config. None for "
        "global actions like water_all, go_home, emergency_stop.",
    )
    params: Dict[str, Any] = Field(
        default_factory=dict,
        description="Action-specific parameters. e.g. {'duration_s': 6} for "
        "water, {'x','y','z'} for raw move. The Pi resolves named targets to "
        "coordinates from its own farmbot.yaml — clients should not embed "
        "coordinates unless they have a reason to override.",
    )
    response: str = Field(
        default="Done.",
        description="Short friendly reply for TTS playback after this intent "
        "completes. Generated by the LLM on the client.",
    )
    question: Optional[str] = Field(
        default=None,
        description="Full natural-language question for general_question "
        "intents. Ignored for other actions.",
    )


class IntentRequest(BaseModel):
    """The full POST /intent payload from a client."""

    intents: List[Intent] = Field(
        ...,
        description="Ordered list — Pi executes them as one sequence tree.",
        min_length=1,
    )
    raw_text: str = Field(
        ...,
        description="The original transcribed utterance, for logging and "
        "post-hoc analysis. Pi does not re-classify this.",
    )
    emergency: bool = Field(
        default=False,
        description="If true, Pi short-circuits to emergency_stop regardless "
        "of `intents`. Clients should set this when the user's words match an "
        "emergency phrase before LLM classification.",
    )
    client_id: str = Field(
        default="unknown",
        description="Stable per-device identifier for logging. No auth.",
    )
    timestamp: datetime = Field(
        default_factory=datetime.utcnow,
        description="Client wall-clock time when the utterance was captured.",
    )
    schema_version: str = Field(
        default=SCHEMA_VERSION,
        description="Wire-format version. Pi rejects mismatched majors.",
    )


class NodeResult(BaseModel):
    """Per-node result inside a `TreeResult`. Mirrors the legacy NodeResult
    in growmate_voice.bt_engine — kept loose so we can serialize either
    dict-based or py_trees results during the migration."""

    name: str
    status: NodeStatus
    message: Optional[str] = None
    duration_ms: Optional[int] = None


class TreeResult(BaseModel):
    """Structured execution trace of one BT tick to completion."""

    label: str = Field(
        ...,
        description="Human-readable tree label, e.g. 'Water tomatoes'.",
    )
    status: TreeStatus
    node_results: List[NodeResult] = Field(default_factory=list)


class IntentResponse(BaseModel):
    """Pi's reply to the client after the tree has finished (or failed).

    When ``status == "running"`` the tree is still executing on the Pi (a
    verified water can take minutes); the client polls
    ``GET /intent_status/{task_id}`` until a terminal status. ``task_id`` is
    set on every reply so the client can correlate / poll.
    """

    status: ResponseStatus
    task_id: Optional[str] = Field(
        default=None,
        description="Server-side id for this execution. Present on async "
        "('running') replies so the client can poll /intent_status/{task_id}.",
    )
    tree: Optional[TreeResult] = None
    commands_published: List[str] = Field(
        default_factory=list,
        description="Raw FarmBot command strings that were published to "
        "`keyboard_topic` during execution. Useful for the client's history "
        "log and for debugging.",
    )
    tts_text: str = Field(
        default="",
        description="Final text the client should speak. Aggregated from the "
        "`response` fields of completed intents.",
    )
    duration_ms: int = 0
    error: Optional[str] = Field(
        default=None,
        description="Set only when status == 'failure'. Brief human-readable "
        "reason — full trace lives in `tree.node_results`.",
    )
    schema_version: str = Field(default=SCHEMA_VERSION)


__all__ = [
    "SCHEMA_VERSION",
    "Action",
    "NodeStatus",
    "TreeStatus",
    "ResponseStatus",
    "Intent",
    "IntentRequest",
    "NodeResult",
    "TreeResult",
    "IntentResponse",
]
