map_reference:
  tools:
    T1: null
    T2: null
    T3: null
    T4: null
    T5: null
    T6: null
  trays: null
  x_len: 5691.2
  y_len: 2734.0
  z_len: 380.08
plant_details:
  plant_count: 42
  plants:
    1:
      identifiers:
        index: 1
        plant_name: Lettuce_little_gem
      plant_details:
        canopy_radius: 12.5
        max_height: 25.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 1100.0
        y: 400.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    2:
      identifiers:
        index: 2
        plant_name: Marigold
      plant_details:
        canopy_radius: 12.5
        max_height: 20.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 1150.0
        y: 750.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    3:
      identifiers:
        index: 3
        plant_name: Marigold
      plant_details:
        canopy_radius: 12.5
        max_height: 20.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 1150.0
        y: 1150.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    4:
      identifiers:
        index: 4
        plant_name: Marigold
      plant_details:
        canopy_radius: 12.5
        max_height: 20.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 1150.0
        y: 1600.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    5:
      identifiers:
        index: 5
        plant_name: Marigold
      plant_details:
        canopy_radius: 12.5
        max_height: 20.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 1150.0
        y: 1850.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    6:
      identifiers:
        index: 6
        plant_name: Marigold
      plant_details:
        canopy_radius: 12.5
        max_height: 20.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 1150.0
        y: 2050.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    7:
      identifiers:
        index: 7
        plant_name: Marigold
      plant_details:
        canopy_radius: 12.5
        max_height: 20.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 1100.0
        y: 2400.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    8:
      identifiers:
        index: 8
        plant_name: Lettuce_little_gem
      plant_details:
        canopy_radius: 12.5
        max_height: 25.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 1850.0
        y: 2400.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    9:
      identifiers:
        index: 9
        plant_name: Lettuce_little_gem
      plant_details:
        canopy_radius: 12.5
        max_height: 25.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 1850.0
        y: 2050.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    10:
      identifiers:
        index: 10
        plant_name: Lettuce_little_gem
      plant_details:
        canopy_radius: 12.5
        max_height: 25.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 1850.0
        y: 1750.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    11:
      identifiers:
        index: 11
        plant_name: Lettuce_little_gem
      plant_details:
        canopy_radius: 12.5
        max_height: 25.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 1850.0
        y: 1400.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    12:
      identifiers:
        index: 12
        plant_name: Lettuce_little_gem
      plant_details:
        canopy_radius: 12.5
        max_height: 25.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 1850.0
        y: 1100.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    13:
      identifiers:
        index: 13
        plant_name: Lettuce_little_gem
      plant_details:
        canopy_radius: 12.5
        max_height: 25.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 1850.0
        y: 800.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    14:
      identifiers:
        index: 14
        plant_name: Lettuce_little_gem
      plant_details:
        canopy_radius: 12.5
        max_height: 25.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 1850.0
        y: 550.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    15:
      identifiers:
        index: 15
        plant_name: Scallion
      plant_details:
        canopy_radius: 7.5
        max_height: 30.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 1.0
      position:
        x: 2450.0
        y: 800.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    16:
      identifiers:
        index: 16
        plant_name: Scallion
      plant_details:
        canopy_radius: 7.5
        max_height: 30.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 1.0
      position:
        x: 2400.0
        y: 1450.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    17:
      identifiers:
        index: 17
        plant_name: Scallion
      plant_details:
        canopy_radius: 7.5
        max_height: 30.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 1.0
      position:
        x: 2350.0
        y: 2100.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    18:
      identifiers:
        index: 18
        plant_name: Mixed Pepper
      plant_details:
        canopy_radius: 22.5
        max_height: 75.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 2700.0
        y: 2350.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    19:
      identifiers:
        index: 19
        plant_name: Mixed Pepper
      plant_details:
        canopy_radius: 22.5
        max_height: 75.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 2700.0
        y: 1750.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    20:
      identifiers:
        index: 20
        plant_name: Mixed Pepper
      plant_details:
        canopy_radius: 22.5
        max_height: 75.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 2700.0
        y: 1150.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    21:
      identifiers:
        index: 21
        plant_name: Mixed Pepper
      plant_details:
        canopy_radius: 22.5
        max_height: 75.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 2700.0
        y: 450.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    22:
      identifiers:
        index: 22
        plant_name: Scallion
      plant_details:
        canopy_radius: 7.5
        max_height: 30.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 1.0
      position:
        x: 3100.0
        y: 800.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    23:
      identifiers:
        index: 23
        plant_name: Scallion
      plant_details:
        canopy_radius: 7.5
        max_height: 30.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 1.0
      position:
        x: 3100.0
        y: 1350.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    24:
      identifiers:
        index: 24
        plant_name: Scallion
      plant_details:
        canopy_radius: 7.5
        max_height: 30.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 1.0
      position:
        x: 3100.0
        y: 2050.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    25:
      identifiers:
        index: 25
        plant_name: Mixed Pepper
      plant_details:
        canopy_radius: 22.5
        max_height: 75.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 3450.0
        y: 2350.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    26:
      identifiers:
        index: 26
        plant_name: Mixed Pepper
      plant_details:
        canopy_radius: 22.5
        max_height: 75.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 3450.0
        y: 1750.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    27:
      identifiers:
        index: 27
        plant_name: Mixed Pepper
      plant_details:
        canopy_radius: 22.5
        max_height: 75.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 3450.0
        y: 1150.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    28:
      identifiers:
        index: 28
        plant_name: Mixed Pepper
      plant_details:
        canopy_radius: 22.5
        max_height: 75.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 3450.0
        y: 450.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    29:
      identifiers:
        index: 29
        plant_name: Scallion
      plant_details:
        canopy_radius: 7.5
        max_height: 30.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 1.0
      position:
        x: 3850.0
        y: 950.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    30:
      identifiers:
        index: 30
        plant_name: Scallion
      plant_details:
        canopy_radius: 7.5
        max_height: 30.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 1.0
      position:
        x: 3850.0
        y: 1450.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    31:
      identifiers:
        index: 31
        plant_name: Scallion
      plant_details:
        canopy_radius: 7.5
        max_height: 30.0
        plant_radius: 2.5
        soil_moisture: 0.0
        water_quantity: 1.0
      position:
        x: 3850.0
        y: 2100.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    32:
      identifiers:
        index: 32
        plant_name: Tomato
      plant_details:
        canopy_radius: 30.0
        max_height: 100.0
        plant_radius: 30.0
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 4300.0
        y: 2350.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    33:
      identifiers:
        index: 33
        plant_name: Tomato
      plant_details:
        canopy_radius: 30.0
        max_height: 100.0
        plant_radius: 30.0
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 4250.0
        y: 1850.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    34:
      identifiers:
        index: 34
        plant_name: Tomato
      plant_details:
        canopy_radius: 30.0
        max_height: 100.0
        plant_radius: 30.0
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 4250.0
        y: 1150.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    35:
      identifiers:
        index: 35
        plant_name: Tomato
      plant_details:
        canopy_radius: 30.0
        max_height: 100.0
        plant_radius: 30.0
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 4250.0
        y: 550.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    36:
      identifiers:
        index: 36
        plant_name: Tomato
      plant_details:
        canopy_radius: 30.0
        max_height: 100.0
        plant_radius: 30.0
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 4750.0
        y: 950.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    37:
      identifiers:
        index: 37
        plant_name: Tomato
      plant_details:
        canopy_radius: 30.0
        max_height: 100.0
        plant_radius: 30.0
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 4700.0
        y: 1550.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    38:
      identifiers:
        index: 38
        plant_name: Tomato
      plant_details:
        canopy_radius: 30.0
        max_height: 100.0
        plant_radius: 30.0
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 4700.0
        y: 2150.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    39:
      identifiers:
        index: 39
        plant_name: Tomato
      plant_details:
        canopy_radius: 30.0
        max_height: 100.0
        plant_radius: 30.0
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 5050.0
        y: 2300.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    40:
      identifiers:
        index: 40
        plant_name: Tomato
      plant_details:
        canopy_radius: 30.0
        max_height: 100.0
        plant_radius: 30.0
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 5050.0
        y: 1750.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    41:
      identifiers:
        index: 41
        plant_name: Tomato
      plant_details:
        canopy_radius: 30.0
        max_height: 100.0
        plant_radius: 30.0
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 5100.0
        y: 1150.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
    42:
      identifiers:
        index: 42
        plant_name: Tomato
      plant_details:
        canopy_radius: 30.0
        max_height: 100.0
        plant_radius: 30.0
        soil_moisture: 0.0
        water_quantity: 2.0
      position:
        x: 5050.0
        y: 550.0
        z: 0.0
      status:
        growth_stage: Seedling
        plant_date:
          day: 0
          month: 0
          year: 0
  weeds: null
