Tomato:
  dry: 3
  average: 2
  wet: 1
Marigold:
  dry: 1
  average: 1
  wet: 0
Basil:
  dry: 3
  average: 2
  wet: 1
Radish:
  dry: 3
  average: 2
  wet: 1
Lettuce_little_gem:
  dry: 2
  average: 1
  wet: 0
Scallion:
  dry: 1
  average: 1
  wet: 0
Mixed Pepper:
  dry: 3
  average: 2
  wet: 1
